export const BUILD_VERSION = '2026.05.29-186'
const BUILD_COMMIT = import.meta.env.VITE_COMMIT_SHA?.trim()
export const BUILD_VERSION_DISPLAY = BUILD_COMMIT ? `${BUILD_VERSION}-${BUILD_COMMIT}` : BUILD_VERSION
