import type { AuthRole } from '@/domains/auth/types'

export const paths = {
  public: {
    home: '/',
    listings: '/anuncios',
    listingDetails: (slug: string) => `/anuncios/${slug}`,
    listingPreview: (id: string) => `/anuncios/preview/${id}`,
    categories: '/categorias',
    categoryDetails: (slug: string) => `/categorias/${slug}`,
    pricing: '/preco-dos-metais-lme',
    scrapPrices: '/tabela-de-precos',
    blog: '/blog',
    blogPost: (slug: string) => `/blog/${slug}`,
    blogPostPreview: (id: string) => `/blog/preview/${id}`,
    about: '/sobre',
    support: '/suporte',
    contact: '/contato',
  },
  auth: {
    login: '/login',
    register: '/cadastro',
    forgotPassword: '/recuperar-senha',
  },
  app: {
    root: '/app',
    listings: '/app/anuncios',
    newListing: '/app/anuncios/novo',
    editListing: (id: string) => `/app/anuncios/${id}/editar`,
    questions: '/app/perguntas',
    notifications: '/app/notificacoes',
    support: '/app/suporte',
    supportDetail: (id: string) => `/app/suporte/${id}`,
    profile: '/app/perfil',
  },
  admin: {
    root: '/admin',
    listings: '/admin/anuncios',
    tutorials: '/admin/tutoriais',
    newListing: '/admin/anuncios/novo',
    editListing: (id: string) => `/admin/anuncios/${id}/editar`,
    listingDetails: (id: string) => `/admin/anuncios/${id}`,
    questions: '/admin/perguntas',
    users: '/admin/usuarios',
    analytics: '/admin/estatisticas',
    contactMessages: '/admin/contato',
    support: '/admin/suporte',
    supportDetail: (id: string) => `/admin/suporte/${id}`,
    notifications: '/admin/notificacoes',
    categories: '/admin/categorias',
    materials: '/admin/materiais',
    locations: '/admin/localidades',
    pages: '/admin/paginas',
    blog: '/admin/blog',
    featuredPayments: '/admin/pagamentos',
    pricing: '/admin/precos',
    scrapPrices: '/admin/preco-das-sucatas',
    settings: '/admin/configuracoes',
    logs: '/admin/logs',
  },
} as const

export function getDefaultPathByRole(role: AuthRole) {
  return role === 'admin' ? paths.admin.root : paths.app.root
}
