delete from public.scrap_price_items;

insert into public.scrap_price_items (product_name, price_label, quantity_label, sort_order, is_active)
values
  ('Aço Inox', 'R$ 4,10', 'Kg', 1, true),
  ('Alumínio Chaparia Limpa', 'R$ 9,00', 'Kg', 2, true),
  ('Alumínio Latinha', 'R$ 10,30', 'Kg', 3, true),
  ('Alumínio Panela (sem cabo e ferro)', 'R$ 10,80', 'Kg', 4, true),
  ('Alumínio Perfil Natural Limpo', 'R$ 12,50', 'Kg', 5, true),
  ('Alumínio Perfil Pintado Limpo', 'R$ 11,30', 'Kg', 6, true),
  ('Bismuto', 'R$ (Sob Análise)', 'kg', 7, true),
  ('Bloco (Limpo)', 'R$ 7,70', 'Kg', 8, true),
  ('Bronze', 'R$ 37,00', 'Kg', 9, true),
  ('Chumbo Manta', 'R$ 4,70', 'Kg', 10, true),
  ('Cobre Mel', 'R$ 57,00', 'Kg', 11, true),
  ('Cobre Misto', 'R$ 53,00', 'Kg', 12, true),
  ('Estanho preço por kg', 'R$120,00', 'kg', 13, true),
  ('Ferro molibdenio preço', 'R$ (Sob Análise)', 'Kg', 14, true),
  ('Ferro Níquel', 'R$ 10,00', 'Kg', 15, true),
  ('Metal', 'R$ 30,00', 'Kg', 16, true),
  ('Radiador de Alumínio e Cobre', 'R$ 24,00', 'Kg', 17, true),
  ('Radiador de Alumínio e Cobre s/ Ferro', 'R$ 23,00', 'Kg', 18, true),
  ('Sucata de Metal Duro', 'R$ (Sob Análise)', 'Kg', 19, true),
  ('Sucata de níquel', 'R$ 75,00', 'Kg', 20, true),
  ('Sucata de Tungstenio Preço', 'R$ (Sob Análise)', 'Kg', 21, true),
  ('Sucata Ferro', 'R$ 0,50', 'Kg', 22, true),
  ('Sucata Ferro Fundido', 'R$ (Sob Análise)', 'Kg', 23, true),
  ('Sucatas de Cobalto', 'R$ (Sob Análise)', 'Kg', 24, true),
  ('Sucatas de Vanadio', 'R$ (Sob Análise)', 'Kg', 25, true),
  ('Varredura de cobre', 'R$ 6,50', 'kg', 26, true),
  ('Zamak e Zinco', 'R$ 10,00', 'Kg', 27, true);
