insert into public.listing_categories (name, slug, description, sort_order)
values
  ('Eu Compro', 'eu-compro', 'Categorias de compra organizadas por segmento.', 5),
  ('Catalizadores Automotivos', 'catalizadores-automotivos-eu-compro', 'Compra de catalizadores automotivos e peças relacionadas.', 10),
  ('Diversos', 'diversos-eu-compro', 'Categorias variadas de compra sem segmentação específica.', 20),
  ('Empilhadeiras', 'empilhadeiras-eu-compro', 'Compra de empilhadeiras e equipamentos de movimentação.', 30),
  ('Máquinas Novas', 'maquinas-novas-eu-compro', 'Compra de máquinas novas ou sem uso operacional.', 40),
  ('Máquinas Usadas', 'maquinas-usadas-eu-compro', 'Compra de máquinas usadas, recuperadas ou seminovas.', 50),
  ('Minérios em Geral', 'minerios-em-geral-eu-compro', 'Compra de minérios e materiais minerais diversos.', 60),
  ('Motores Diversos', 'motores-diversos-eu-compro', 'Compra de motores de vários portes e aplicações.', 70),
  ('Plásticos', 'plasticos-eu-compro', 'Compra de plásticos e resíduos plásticos em geral.', 80),
  ('Resíduos em Geral', 'residuos-em-geral-eu-compro', 'Compra de resíduos diversos e materiais mistos.', 90),
  ('Sucata de Alumínio', 'sucata-de-aluminio-eu-compro', 'Compra de sucata de alumínio e ligas correlatas.', 100),
  ('Sucata de Chumbo', 'sucata-de-chumbo-eu-compro', 'Compra de sucata de chumbo e derivados.', 110),
  ('Sucata de Cobre', 'sucata-de-cobre-eu-compro', 'Compra de sucata de cobre e materiais afins.', 120),
  ('Sucata de Eletrônica', 'sucata-de-eletronica-eu-compro', 'Compra de sucata eletrônica, placas e componentes.', 130),
  ('Sucata de Estanho', 'sucata-de-estanho-eu-compro', 'Compra de sucata de estanho e ligas com estanho.', 140),
  ('Sucata de Ferro', 'sucata-de-ferro-eu-compro', 'Compra de sucata de ferro e aço.', 150),
  ('Sucata de Inox', 'sucata-de-inox-eu-compro', 'Compra de sucata de inox e aço inoxidável.', 160),
  ('Sucata de Magnésio', 'sucata-de-magnesio-eu-compro', 'Compra de sucata de magnésio e ligas leves.', 170),
  ('Sucata de Molibdênio', 'sucata-de-molibdenio-eu-compro', 'Compra de sucata de molibdênio e ligas especiais.', 180),
  ('Sucata de Níquel', 'sucata-de-niquel-eu-compro', 'Compra de sucata de níquel e materiais relacionados.', 190),
  ('Sucata de Zamac', 'sucata-de-zamac-eu-compro', 'Compra de sucata de zamac e ligas de zinco.', 200),
  ('Serviços', 'servicos', 'Serviços relacionados ao mercado de sucatas e maquinários.', 210),
  ('Venda', 'venda', 'Categorias de venda organizadas por segmento.', 220),
  ('Catalizadores Automotivos', 'catalizadores-automotivos', 'Venda de catalizadores automotivos e peças relacionadas.', 230),
  ('Diversos', 'diversos', 'Categorias variadas de venda sem segmentação específica.', 240),
  ('Empilhadeiras', 'empilhadeiras', 'Venda de empilhadeiras e equipamentos de movimentação.', 250),
  ('Máquinas Novas', 'maquinas-novas', 'Venda de máquinas novas ou sem uso operacional.', 260),
  ('Máquinas Usadas', 'maquinas-usadas', 'Venda de máquinas usadas, recuperadas ou seminovas.', 270),
  ('Minérios em Geral', 'minerios-em-geral', 'Venda de minérios e materiais minerais diversos.', 280),
  ('Motores Diversos', 'motores-diversos', 'Venda de motores de vários portes e aplicações.', 290),
  ('Plásticos', 'plasticos', 'Venda de plásticos e resíduos plásticos em geral.', 300),
  ('Resíduos em Geral', 'residuos-em-geral', 'Venda de resíduos diversos e materiais mistos.', 310),
  ('Sucata de Alumínio', 'sucata-de-aluminio', 'Venda de sucata de alumínio e ligas correlatas.', 320),
  ('Sucata de Chumbo', 'sucata-de-chumbo', 'Venda de sucata de chumbo e derivados.', 330),
  ('Sucata de Cobre', 'sucata-de-cobre', 'Venda de sucata de cobre e materiais afins.', 340),
  ('Sucata de Eletrônica', 'sucata-de-eletronica', 'Venda de sucata eletrônica, placas e componentes.', 350),
  ('Sucata de Estanho', 'sucata-de-estanho', 'Venda de sucata de estanho e ligas com estanho.', 360),
  ('Sucata de Ferro', 'sucata-de-ferro', 'Venda de sucata de ferro e aço.', 370),
  ('Sucata de Inox', 'sucata-de-inox', 'Venda de sucata de inox e aço inoxidável.', 380),
  ('Sucata de Magnésio', 'sucata-de-magnesio', 'Venda de sucata de magnésio e ligas leves.', 390),
  ('Sucata de Molibdênio', 'sucata-de-molibdenio', 'Venda de sucata de molibdênio e ligas especiais.', 400),
  ('Sucata de Níquel', 'sucata-de-niquel', 'Venda de sucata de níquel e materiais relacionados.', 410),
  ('Sucata de Zamac', 'sucata-de-zamac', 'Venda de sucata de zamac e ligas de zinco.', 420)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
