import { paths } from '@/app/paths'
import type { SitePageDefinition } from '@/domains/site-pages/types'

export const PUBLIC_SITE_PAGE_DEFINITIONS: SitePageDefinition[] = [
  {
    description: 'Página inicial e apresentação da plataforma.',
    key: 'home',
    path: paths.public.home,
    section: 'Institucional',
    sortOrder: 10,
    source: 'site_pages',
    title: 'Home',
  },
  {
    description: 'Catálogo público de anúncios aprovados.',
    key: 'listings',
    path: paths.public.listings,
    section: 'Comercial',
    sortOrder: 20,
    source: 'site_pages',
    title: 'Anúncios',
  },
  {
    description: 'Navegação por categorias de sucata e materiais.',
    key: 'categories',
    path: paths.public.categories,
    section: 'Comercial',
    sortOrder: 30,
    source: 'site_pages',
    title: 'Categorias',
  },
  {
    description: 'Referência pública de preços e cotação de metais.',
    key: 'pricing',
    path: paths.public.pricing,
    section: 'Comercial',
    sortOrder: 40,
    source: 'site_pages',
    title: 'Cotação LME',
  },
  {
    description: 'Tabela pública de preços de sucatas e materiais.',
    key: 'scrap_prices',
    path: paths.public.scrapPrices,
    section: 'Comercial',
    sortOrder: 50,
    source: 'site_pages',
    title: 'Preços dos Metais',
  },
  {
    description: 'Apresentação institucional da Zap Sucatas.',
    key: 'about',
    path: paths.public.about,
    section: 'Institucional',
    sortOrder: 60,
    source: 'site_pages',
    title: 'Sobre',
  },
  {
    description: 'Formulário e canais de contato com o time.',
    key: 'contact',
    path: paths.public.contact,
    section: 'Relacionamento',
    sortOrder: 70,
    source: 'site_pages',
    title: 'Contato',
  },
  {
    description: 'Canal público de suporte e orientação.',
    key: 'support',
    path: paths.public.support,
    section: 'Relacionamento',
    sortOrder: 80,
    source: 'site_pages',
    title: 'Suporte',
  },
  {
    description: 'Conteúdo editorial e SEO.',
    key: 'blog',
    path: paths.public.blog,
    section: 'Conteúdo',
    sortOrder: 90,
    source: 'system_settings',
    title: 'Blog',
  },
]
